language: node_js

node_js:
  - "12"

git:
  depth: 100

cache: false

branches:
  only:
    - master

before_install:
  - START_TIME=$(date +%s)
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -k "$ssh_key_decrypt_password" -in id_rsa.enc -out $HOME/.ssh/id_rsa -d
  - chmod 600 $HOME/.ssh/id_rsa
  - ssh-add $HOME/.ssh/id_rsa
  - git config --global user.email bot@example.com
  - git config --global user.name bot
  - git remote set-url origin git@github.com:2049bbs/2049bbs.github.io.git

install:
  - npm install

before_script:
  - git fetch
  - git checkout -f master

script:
  - npm run backup
  - git pull
  - git add .
  - git commit -m "$(date --iso-8601=minutes -u) [skip ci]"
  - git push

after_script:
  - FINISH_TIME=$(date +%s)
  - WAITING_MIN=$(( 15 - ((FINISH_TIME - START_TIME) / 60) - 1 ))
  - for i in $(seq $WAITING_MIN -1 1); do
      echo "Waiting. $i minute(s) left.";
      sleep 60;
    done

stages:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  - 73
  - 74
  - 75
  - 76
  - 77
  - 78
  - 79
  - 80
  - 81
  - 82
  - 83
  - 84
  - 85
  - 86
  - 87
  - 88
  - 89
  - 90
  - 91
  - 92
  - 93
  - 94
  - 95
  - 96

jobs:
  allow_failures:
    - node_js: "12"
  include:
  # * 96
    - stage: 1
    - stage: 2
    - stage: 3
    - stage: 4
    - stage: 5
    - stage: 6
    - stage: 7
    - stage: 8
    - stage: 9
    - stage: 10
    - stage: 11
    - stage: 12
    - stage: 13
    - stage: 14
    - stage: 15
    - stage: 16
    - stage: 17
    - stage: 18
    - stage: 19
    - stage: 20
    - stage: 21
    - stage: 22
    - stage: 23
    - stage: 24
    - stage: 25
    - stage: 26
    - stage: 27
    - stage: 28
    - stage: 29
    - stage: 30
    - stage: 31
    - stage: 32
    - stage: 33
    - stage: 34
    - stage: 35
    - stage: 36
    - stage: 37
    - stage: 38
    - stage: 39
    - stage: 40
    - stage: 41
    - stage: 42
    - stage: 43
    - stage: 44
    - stage: 45
    - stage: 46
    - stage: 47
    - stage: 48
    - stage: 49
    - stage: 50
    - stage: 51
    - stage: 52
    - stage: 53
    - stage: 54
    - stage: 55
    - stage: 56
    - stage: 57
    - stage: 58
    - stage: 59
    - stage: 60
    - stage: 61
    - stage: 62
    - stage: 63
    - stage: 64
    - stage: 65
    - stage: 66
    - stage: 67
    - stage: 68
    - stage: 69
    - stage: 70
    - stage: 71
    - stage: 72
    - stage: 73
    - stage: 74
    - stage: 75
    - stage: 76
    - stage: 77
    - stage: 78
    - stage: 79
    - stage: 80
    - stage: 81
    - stage: 82
    - stage: 83
    - stage: 84
    - stage: 85
    - stage: 86
    - stage: 87
    - stage: 88
    - stage: 89
    - stage: 90
    - stage: 91
    - stage: 92
    - stage: 93
    - stage: 94
    - stage: 95
    - stage: 96
